### PR TITLE
added interactive plot with ipywidgets

### PR DESCRIPTION
**Pull request by stevejpurves**
@kaylai I split out the interactive plot into a separate notebook and renamed your original to indicate that it was about data preparation. The new notebook now produces this:

eOPTwVP5pD

### CODE REVIEW

**Comment by stevejpurves** [comment]
Please let me know if anything (like title, markdown content etc... ) needs to be changed

**Comment by kaylai** [comment]
Looks amazing, Steve! I added VESIcal to the requirements.txt file and just tweaked the labels on the plot, then I merged the PR.

**Comment by kaylai** [comment]
I'll throw another idea out there for intractability. The isobars calculated for each of those points vary because the chemical composition of each point is different. In the figure below, you can see the same points plotted to show their composition. Is it possible to connect two plots, e.g., in a subplot, so that when a point is clicked in Plot A it highlights in both Plot A and Plot B? Even taking one of the plots from this figure could give the user an idea of what chemical parameters are changing that produce those different isobar curves. SiO2 vs MgO might be a good one.
Figure10

**Comment by stevejpurves** [comment]
thanks @kaylai I've incorporated your first set of changes, will share a link soon to the latest content... linking plots is totally doable, I'll see if we can work that in!

**Comment by kaylai** [comment]
Radical 🤓

**Pull request merged**
